### ISSUE TITLE
[NPC] High Chief Winterfall

### ISSUE THREAD

**Issue by ZaoQ** [SunwellWoW/Sunwell-TBC-Bugtracker#2457]
Description: 
He should drop Crudely-written Log with 100% drop rate.

How it works: 
He does not.

How it should work: 

Source (you should point out proofs of your report, please give us some source): 
https://tbc-twinhead.twinstar.cz/?item=12842

**Comment by Dootz** [comment]
https://www.wowhead.com/item=12842/crudely-written-log#comments:id=118155

> Only drops when killing him for the quest, not normally.

**Comment by ZaoQ** [comment]
It didnt drop when i did the Q ... 
![wowscrnshot_120418_235454](https://user-images.githubusercontent.com/45085629/49478481-22b92100-f820-11e8-8bd3-8495b7e70ff2.jpg)

**Comment by badmannerkid** [comment]
yeah, same with me. it won't drop still

**Comment by badmannerkid** [comment]
tried killing him while i held the quest Winterfall Runners and then tried again to kill him while I held the quest High Chief Winterfall. still wouldn't drop the book

**Comment by 0vertime** [comment]
Was wondering why this wasn't dropping. Hope it's going to drop while already having done the chain.

**Comment by Dootz** [comment]
fixed and implemented. Thank you for report.

**Comment by ZaoQ** [comment]
![wowscrnshot_120918_204528](https://user-images.githubusercontent.com/45085629/49702023-2a980d00-fbf4-11e8-8648-90a2f9fb3bcb.jpg)
![wowscrnshot_120918_204552](https://user-images.githubusercontent.com/45085629/49702027-2d92fd80-fbf4-11e8-977e-260f943421a8.jpg)
Still doesnt work guys ... :(((

**Comment by Wojtyas** [comment]
Works now ;)
